# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool: mypool

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    cd src
    dotnet restore
    dotnet build --no-restore --configuration $(buildConfiguration)
  displayName: 'restore and build'

