
name: asynchandler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  azuresqlenv: ${{ secrets.AZURESQLDATABASE }}
  mssqlenv: "Server=localhost,1433;Initial Catalog=asynchandler;Persist Security Info=False;User ID=sa;Password=sysadmin@2024;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=true;Connection Timeout=10;"
  mssql_db: asynchandler
  mssql_password: sysadmin@2024

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: true
          MSSQL_SA_PASSWORD: ${{ env.mssql_password }}

    steps:
    - uses: actions/checkout@v4

    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: 8.0.x
    # - name: Restore dependencies
    #   run: dotnet restore
    # - name: Build
    #   run: dotnet build --no-restore

    - name: create db
      run: ./build.sh

    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
